### ISSUE TITLE
Ревью кода

### ISSUE THREAD

**Issue by BaH3eP** [delet-dis/neumorphism-calculator#1]
1. Не должно быть никаких глобальных переменных. Переменные должны быть только внутри того класса, в котором они используются.

2. Для каждой кнопки ставится отдельный лисенер, хотя логика в них одна и та же: записать значение текста самой кнопки в отдельное поле. Можно создать группу в xml разметке и поместить в нее все кнопки с одинаковой логикой (пока что только кнопки цифр). После, в классе активности обращаясь к группе написать один единственный onClickListener с логикой 
`calculator_display_non_mock.text =
                calculator_display_non_mock.text.toString() + (it as? Button).text.toString()`

3. Примерно тоже самое, что я описал выше, можно сделать и с кнопками операций

4. Обработка ошибки есть только в некоторых лисенерах. Так, к примеру, если я жму несколько раз на кнопку плюс, то приложение просто вылетает, а вылет приложения -- смерть для мобильного разработчика

5. Название операций определяется по входной строке. Если ты где-нибудь сделаешь опечатку, то долго будешь отлавливать ошибку. Все строковые константы должны быть в отдельных константных переменных. В твоем же случае лучше сделать отдельный enum class Operation, в котором будут описаны возможные операции. И уже в функцию onClickOperation передавать нужный тебе enum элемент.

6. В коде xml находятся элементы, которые предназначены для телефонов с версией api выше, чем минимальная в проекте. Так лучше не делать, потому что для телефонов с api 26 не будет работать то, что работает на api 28.

7. Не понимаю логику того, что в mock_text'е куча запятых, которые ты потом еще и меняешь на нужные тебе значения.  Это вообще не понятно для стороннего программиста и так лучше не делать. Не лучше ли тогда просто оставить его пустым и записывать нужные значения?

8. Так как ты пишешь на котлине, то и наименование переменных в xml тоже нужно придерживаться котлиновских, а именно использовать верблюжью нотацию (вместо calculator_display_non_mock писать calculatorDisplayNonMock)

**Comment by delet-dis** [comment]
Исправлено
