### ISSUE TITLE
Ревью кода #2

### ISSUE THREAD

**Issue by BaH3eP** [delet-dis/neumorphism-calculator#2]
1. Один файл — один класс (исключением могут быть, если есть множество дата классов или функций объединенных одной логикой). А это означает, что `enum Operation `должен находится либо внутри активности, либо в отдельном файле в студии

2. Лучше инициализацию лисенеров переместить в отдельную функцию` initListeners()`. В `onCreate` должны находится базовые функции, которые можно будет прочитать и примерно понять что происходит в активности. 

К примеру очень часто бывает: "`initView() initListeners() initAdapters() observeViewModel()`" в `onCreate` и тогда человеку сразу ясно что проиходит в основном в активности и где. "Ага, тут инициализирует вью, тут устанавливает лисенеры, тут устанавливает адаптеры, а потом делает какую-то логику" 

3. В `onClickOperation ` ты все равно принимаешь строку, а это означает, что другой программист вызовет `onClickOperation("хочу арбуз")` и словит ошибку сказав, что это ты неправильно написал функцию. Поэтому функция должна выглядеть вот так `onClickOperation(processingOperation: Operation)` и уже внутри разруливать с этим атрибутом так, как тебе нужно

4. `if (isAvailableToOperate()) {
                onClickOperation(Любая_переменная)
            }`
Этот кусок кода часто повторяется, хотя тут меняется только одна переменная. Нужно сделать отдельную функцию, куда ты будешь просто передавать нужный тебе параметр (для деления DIVIDE, для умножения MULTIPLY и тд)

5. Переименуй переменные `val1` и `val2`, т.к. не понятно за что они отвечают. Это две разные цифры, или предыдущее и текущее значение? Чтобы таких вопросов не возникало нужно сразу именовать переменные таким образом, чтобы было понятно что в ней лежит

6. В логике описания нажатия кнопки минуса 3 раза повторяется `calculatorDisplayNonMock.text.toString()` в одном ифе. Лучше вынеси это в отдельную переменную, и тогда тебе не придется постоянно писать огромный текст, так еще и работать будет быстрее, потому что сделал преобразование только один раз, а не несколько

7. Магическая константа 2 в обработке логики кнопки минус. Почему 2? Что за 2? Почему она там? Я, честно говоря, до сих пор и не понял)

8. В котлине есть очень удобный способ конкатинации строк. Вместо того, чтобы писать `"str1" + "-" + "str2"` можно писать `"$str1 - $str2"`. Если str1 будет не просто переменной, а какой-нибудь `str1.toSth().toString()`, то можно использовать фигурные скобки `"${str1.toSth().toString()} - $str2"`

9. Все еще не понятно почему у тебя один из textView напичкан запятыми и ты их реплейсишь. Оставь коммент в этом случае, это сильно упростит работу другим людям

**Comment by delet-dis** [comment]
Насчет последнего. У меня два моковых поля для подложки(выделил на скриншоте), которые я использую, чтобы сделать эффект экрана, как на макете, а, я изменяю третье, что подсвечено
![image](https://user-images.githubusercontent.com/47276603/100899524-87cdad00-34f4-11eb-9bb2-ccf5f8c3c931.png)

**Comment by delet-dis** [comment]
Все пункты причесаны

**Comment by BaH3eP** [comment]
Переменная operation, которая в начале активности объявлена, должна быть типом Operation, а не строкой. Поправь этот момент, и в целом уже хорошо

**Comment by delet-dis** [comment]
Готово!
